# Generated by Django 4.1.7 on 2023-04-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateField(auto_created=True)),
                ("meta_universalid", models.UUIDField()),
                ("file_name", models.CharField(max_length=150)),
            ],
        ),
    ]
